apiVersion: v1
kind: Secret
metadata:
  name: spektra-control-plane-{{ .Values.spec.controlPlaneCert.type }}
  namespace: "{{ .Values.namespace }}"
type: Opaque
data:
  crt: "{{ .Values.spec.controlPlaneCert.crt }}"
  key: "{{ .Values.spec.controlPlaneCert.key }}"
  aws-ssl-cert-arn: "{{ .Values.spec.controlPlaneCert.awsSslCertArn | b64enc }}"
